### ISSUE TITLE
sphinx-design 0.6.1 is not compatible with sphinx 8

### ISSUE THREAD

**Issue by sblauth** [conda-forge/sphinx-design-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With release 0.6.1, sphinx-design 0.6.1 supports sphinx 8. However, I noticed that the recipe here still has a restriction to
```
    - sphinx >=5,<8
```

e.g. here https://github.com/conda-forge/sphinx-design-feedstock/blob/main/recipe/meta.yaml#L26C1-L26C20

Therefore, it is currently not possible to install sphinx-design 0.6.1 with sphinx 8 from conda-forge.

### Installed packages

```shell
Not relevant
```

### Environment info

```shell
Not relevant
```

**Comment by raphaelquast** [comment]
Hey @sblauth 
Since I had the same issue, made a quick PR to fix this and it's already merged!.
Happy to report that 0.6.1 is now compatible with sphinx v8 also on conda-forge!
